const dataBase = [
  "God",
  "Men",
  "Woman",
  "Humanity",
  "Dog",
  "Cat",
  "Vegetable",
  "Fruit",
  "Water",
  "Food",
  "Shelter",
  "Clothing",
  "Medicine",
  "Phone",
  "Computer",
  "Vehicle",
  "Electricity",
  "Internet",
  "Tools",
  "Books",
  "Money",
  "Watch",
  "Keys",
  "Bed",
  "Chair",
  "Table",
  "Shoes",
  "Glasses",
  "Lion",
  "Elephant",
  "Tiger",
  "Panda",
  "Dolphin",
  "Kangaroo",
  "Giraffe",
  "Penguin",
  "Polar Bear",
  "Gorilla",
  "Wolf",
  "Eagle",
  "Shark",
  "Whale",
  "Cheetah",
  "Leopard",
  "Rhinoceros",
  "Chimpanzee",
  "Zebra",
  "Crocodile",
  "Artificial Intelligence",
  "Quantum Computing",
  "Virtual Reality",
  "Space Colonization",
  "Nanotechnology",
  "Teleportation",
  "Time Travel",
  "Cybernetic Enhancement",
  "Genetic Engineering",
  "Mind Uploading",
  "Autonomous Vehicles",
  "Cryonics",
  "Smart Cities",
  "Brain-Computer Interface",
  "Fusion Energy",
  "Robot Companions",
  "Cloning",
  "Augmented Reality",
  "Global AI Governance",
  "Interstellar Travel",
  "Humanoid Robots",
  "Autonomous Drones",
  "Industrial Robots",
  "3D Printers",
  "Exoskeletons",
  "Robotic Arms",
  "Self-Driving Cars",
  "Service Robots",
  "Bionic Limbs",
  "AI Assistants",
  "Surgical Robots",
  "Factory Automation",
  "Delivery Robots",
  "Cleaning Robots",
  "Smart Home Devices",
  "Automated Assembly Lines",
  "Flying Cars",
  "Agricultural Robots",
  "Military Drones",
  "Robotic Pets",
  "Angels",
  "Demons",
  "Archangels",
  "Cherubim",
  "Seraphim",
  "Fallen Angels",
  "Ghosts",
  "Spirits",
  "Goblins",
  "Fairies",
  "Dragons",
  "Witches",
  "Vampires",
  "Werewolves",
  "Shapeshifters",
  "Imps",
  "Genies",
  "Poltergeists",
  "Reapers",
  "Deities",
  "Butterfly",
  "Bee",
  "Ladybug",
  "Ant",
  "Dragonfly",
  "Mosquito",
  "Moth",
  "Cockroach",
  "Grasshopper",
  "Fly",
  "Beetle",
  "Wasp",
  "Termite",
  "Cricket",
  "Firefly",
  "Spider",
  "Hornet",
  "Silverfish",
  "Flea",
  "Bedbug",
];
const ideas = document.querySelector(".ideas");
let generateIdea = (element) => {
  element.addEventListener("click", () => {
    const randomNum = Math.floor(Math.random() * dataBase.length);
    ideas.textContent = `${dataBase[randomNum]}`;
  });
};
const button = document.querySelector("#generate");
generateIdea(button);
